#ifndef ErrorCode_H
#define ErrorCode_H

typedef enum
{
  ERR_NO_ERROR,
	ERR_EXCEEDED_INDEX,
  ERR_EMPTY_COURSE,
  ERR_EXCEEDED_VENUE_INDEX,
  ERR_EXCEEDED_DAY_INDEX,
  ERR_EXCEEDED_TIME_INDEX,
  ERR_INVALID_TYPE
} ErrorCode;

#endif // ErrorCode_H